# Layer Rules — Controle centralizado de separação de conteúdo
version: "2.0"

layers:
  layer1:
    name: "Community"
    remote: "public"
    repo: "mega-brain.git"
    description: "Shell público distribuído via npm"
    rule: "Apenas arquivos NÃO ignorados pelo .gitignore"
    npm_publish: true

  layer2:
    name: "Premium"
    remote: "premium"
    repo: "mega-brain-premium.git"
    description: "Shell + conteúdo premium (MoneyClub)"
    rule: "Layer 1 + paths listados em layer2-manifest.txt"
    npm_publish: false

  layer3:
    name: "Full Backup"
    remote: "backup"
    repo: "mega-brain-full.git"
    description: "Backup completo incluindo dados pessoais"
    rule: "TUDO sem exceção"
    npm_publish: false

excluded_personas:
  - g4-educacao
  - full-sales-system
  - grupo-silva

forbidden_patterns:
  layer1:
    - pattern: "github_pat_"
      severity: CRITICAL
    - pattern: "sk-ant-"
      severity: CRITICAL
    - pattern: "/Users/thiagofinch"
      severity: HIGH
    - pattern: "C:\\Users\\thiago"
      severity: HIGH
  layer2:
    - pattern: "g4-educacao"
      severity: HIGH
      context: "files_only"
    - pattern: "full-sales-system"
      severity: HIGH
      context: "files_only"
    - pattern: "grupo-silva"
      severity: HIGH
      context: "files_only"

auto_sync:
  on_layer1_push: [layer3]
  on_layer2_push: [layer3]
  on_layer3_push: []
