"""agent_skeleton.py -- Auto-create minimal agent skeleton for new slugs
=======================================================================

G18 (2026-05-13): when the MCE pipeline finalizes a slug whose person agent
does NOT exist yet, downstream cascading + memory enrichment silently emit
``0 appended`` because there is no ``agents/{bucket}/{slug}/`` to target.

This module creates the minimal four-file skeleton expected by the agent
boot sequence (AGENT.md → SOUL.md → MEMORY.md → DNA-CONFIG.yaml) so that
``memory_enricher.enrich_from_insights_state`` finds a valid target on the
very first run.

Skeletons are EXPLICITLY marked as auto-generated ("status: skeleton"). They
are NOT mind-clones until populated by subsequent cascade enrichment and
human review.

Contract:
    - Idempotent: never overwrites an existing agent directory.
    - Non-fatal: any exception is logged and ``created=False`` is returned.
    - Confined to ``agents/external/`` and ``agents/business/`` (no personal).
    - Files are minimal-by-design: SOUL/AGENT are templates, MEMORY is the
      same stub the enricher would create, DNA-CONFIG references the canonical
      DNA artifact path under ``knowledge/{bucket}/dna/persons/{slug}/``.

Version: 1.0.0
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from engine.paths import ROOT

logger = logging.getLogger("mce.agent_skeleton")


_AGENT_MD_TEMPLATE = """\
---
id: {slug}
type: external_clone
status: skeleton
auto_generated: true
generated_at: {date}
generator: mce.agent_skeleton v1.0.0
sources_count: {sources_count}
dna_layers_populated: {dna_layers}
version: 0.1.0
---

# {person_name} -- PERSON AGENT (SKELETON)

> Auto-generated skeleton from the MCE pipeline.
> NOT a finalized mind-clone -- the population of voice, behavior, and identity
> happens via post-extraction cascading + human review.

## Status

This file was created automatically when the MCE pipeline finalized
``{slug}`` for the first time and no ``agents/{bucket}/{slug}/`` directory
existed.

Generated artifacts:

- **DNA**: ``knowledge/{bucket}/dna/persons/{slug}/`` ({dna_layers} layers,
  {dna_total} elements)
- **Insights**: ``.data/artifacts/insights/{slug}/INSIGHTS-STATE.json``
- **Chunks**: ``.data/artifacts/chunks/{slug}/``

## Boot Sequence (Read in Order)

1. ``AGENT.md`` (this file)
2. ``SOUL.md`` -- voice + personality (auto-stub)
3. ``DNA-CONFIG.yaml`` -- knowledge source manifest
4. ``MEMORY.md`` -- accumulated insights (populated by cascade)

## Next Actions

- Cascade enrichment will populate ``MEMORY.md`` with extracted insights.
- Subsequent pipeline runs (``brownfield`` mode) will refresh DNA + cascade.
- Human review should promote ``status: skeleton`` -> ``status: active`` once
  the agent has enough material to respond reliably in character.

---

*Auto-generated by ``engine/intelligence/pipeline/mce/agent_skeleton.py`` v1.0.0*
"""


_SOUL_MD_TEMPLATE = """\
---
id: {slug}
status: skeleton
auto_generated: true
generated_at: {date}
---

# {person_name} -- SOUL (SKELETON)

> Voice DNA + personality. This stub will be populated by future iterations
> of the MCE pipeline (Voice DNA layer L8 cascade) and by human authoring.

## Voice (L8 -- placeholder)

*To be populated from ``knowledge/{bucket}/dna/persons/{slug}/L8-VOICE-DNA.yaml``
when that artifact lands.*

## Personality Anchors

- *Anchor 1*: TBD
- *Anchor 2*: TBD
- *Anchor 3*: TBD

## Tone Calibration

- **Default register**: neutral, professional
- **Energy**: medium
- **Idiolect**: not yet captured

## Activation Phrase

*To be defined once voice signature is extracted.*

---

*Auto-generated SOUL stub -- replace with curated content after L8 extraction.*
"""


_MEMORY_MD_TEMPLATE = """\
# MEMORY: {person_name}

> **Atualizado:** {date}
> **Versao:** 1.0.0
> **Status:** skeleton (auto-generated by agent_skeleton.py)

---

## MATERIAIS PROCESSADOS

*Nenhum material processado ainda.*

---

## PADROES DE PENSAMENTO

*A ser populado com processamento de materiais via Pipeline.*

---

## EXPRESSOES CARACTERISTICAS

*Nenhuma expressao identificada ainda.*

---

## INSIGHTS EXTRAIDOS

*Insights do Pipeline serao adicionados aqui automaticamente.*

---

## HISTORICO DE ATUALIZACOES

| Data | Mudanca | Material Processado |
|------|---------|---------------------|
| {date} | Criacao inicial (auto-gerado) | agent_skeleton.py v1.0.0 |

---

*MEMORY.md v1.0.0 - Auto-gerado por ``agent_skeleton.py``*
"""


def get_agent_filenames(agent_dir: Path) -> dict[str, str]:
    """Return canonical filenames for agent files in the given directory.

    MCE-13.6: external/business/personal agents use lowercase filenames.
    Cargo agents (``agents/external/cargo/**``) retain UPPERCASE for
    backward compat (MCE-12.1 carve-out).

    Args:
        agent_dir: Absolute or repo-relative Path to the agent directory.

    Returns:
        Dict with keys ``agent``, ``soul``, ``memory``, ``dna_config``
        mapping to the correct filename for the bucket.
    """
    parts = Path(agent_dir).parts
    is_cargo = "cargo" in parts
    if is_cargo:
        return {
            "agent": "AGENT.md",
            "soul": "SOUL.md",
            "memory": "MEMORY.md",
            "dna_config": "DNA-CONFIG.yaml",
        }
    return {
        "agent": "agent.md",
        "soul": "soul.md",
        "memory": "memory.md",
        "dna_config": "dna-config.yaml",
    }


def _slug_to_person_name(slug: str) -> str:
    """Convert a kebab-case slug to a display name."""
    return " ".join(w.capitalize() for w in slug.split("-"))


def _dna_dir_for_bucket(slug: str, bucket: str):
    """Delegate to the single SOT (STORY-MCE-BUCKET-AWARE-WRITES).

    Previously duplicated orchestrate._dna_dir_for_slug with the deprecated
    convention A (business -> ``people/{slug}``). Now both delegate to
    ``PersonArtifactPaths`` (convention B, ``dna/persons/{slug}``) so the
    skeleton reader never diverges from the writer.
    """
    from engine.intelligence.pipeline.mce.person_paths import PersonArtifactPaths

    return PersonArtifactPaths(slug, bucket, root=ROOT).dna


def _read_dna_summary(slug: str, bucket: str) -> dict[str, Any]:
    """Read DNA-CONFIG.yaml composition for a slug (best-effort)."""
    dna_dir = _dna_dir_for_bucket(slug, bucket)
    dna_path = dna_dir / "DNA-CONFIG.yaml"
    if not dna_path.exists():
        return {}
    try:
        with open(dna_path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
    except Exception as exc:  # pragma: no cover - non-fatal
        logger.debug("Failed to read DNA-CONFIG for %s: %s", slug, exc)
        return {}
    if not isinstance(data, dict):
        return {}
    return data


def create_agent_skeleton(
    slug: str,
    bucket: str,
    *,
    sources_count: int = 0,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Create a minimal agent skeleton for a slug in the given bucket.

    Args:
        slug: Person slug (kebab-case).
        bucket: One of ``"external" | "business"``. ``"personal"`` is rejected
            (personal agents are hand-authored, never auto-generated).
        sources_count: Optional count of source files processed (for AGENT.md
            metadata).
        dry_run: When True, return what WOULD be created without writing.

    Returns:
        Dict with keys:
            - ``created`` (bool): True if a new skeleton was written.
            - ``agent_dir`` (str): Absolute path to the agent directory.
            - ``files`` (list[str]): Files written (or to be written).
            - ``reason`` (str, optional): Reason when ``created=False``.
            - ``error`` (str, optional): Error message on failure.

    Never raises -- caller (cmd_finalize) must remain non-blocking.
    """
    if bucket not in ("external", "business"):
        return {
            "created": False,
            "reason": f"bucket={bucket!r} not eligible for auto-skeleton",
            "agent_dir": "",
            "files": [],
        }

    if not slug or "/" in slug or ".." in slug:
        return {
            "created": False,
            "reason": f"invalid slug={slug!r}",
            "agent_dir": "",
            "files": [],
        }

    agent_dir = ROOT / "agents" / bucket / slug

    if agent_dir.exists():
        return {
            "created": False,
            "reason": "agent directory already exists",
            "agent_dir": str(agent_dir),
            "files": [],
        }

    # Gather DNA evidence -- the entire purpose of auto-skeleton is to capture
    # a slug that has DNA but no agent.  If DNA is missing, skip (the slug is
    # not yet ripe for an agent shell).
    dna_data = _read_dna_summary(slug, bucket)
    if not dna_data:
        _expected_dir = _dna_dir_for_bucket(slug, bucket).relative_to(ROOT)
        return {
            "created": False,
            "reason": f"no DNA-CONFIG.yaml at {_expected_dir}/",
            "agent_dir": str(agent_dir),
            "files": [],
        }

    composition = dna_data.get("composition", {}) if isinstance(dna_data, dict) else {}
    dna_total = composition.get("total", 0) if isinstance(composition, dict) else 0
    dna_layers = (
        len([k for k in composition if k != "total"]) if isinstance(composition, dict) else 0
    )

    person_name = _slug_to_person_name(slug)
    date = datetime.now(UTC).strftime("%Y-%m-%d")

    # MCE-13.6: resolve bucket-aware filenames (lowercase for non-cargo)
    fnames = get_agent_filenames(agent_dir)

    file_plan = {
        fnames["agent"]: _AGENT_MD_TEMPLATE.format(
            slug=slug,
            person_name=person_name,
            bucket=bucket,
            date=date,
            sources_count=sources_count,
            dna_layers=dna_layers,
            dna_total=dna_total,
        ),
        fnames["soul"]: _SOUL_MD_TEMPLATE.format(
            slug=slug,
            person_name=person_name,
            bucket=bucket,
            date=date,
        ),
        fnames["memory"]: _MEMORY_MD_TEMPLATE.format(
            slug=slug,
            person_name=person_name,
            date=date,
        ),
        fnames["dna_config"]: yaml.safe_dump(
            {
                "id": slug,
                "person": person_name,
                "bucket": bucket,
                "status": "skeleton",
                "auto_generated": True,
                "generated_at": date,
                "dna_sources": {
                    "primario": [
                        {
                            "pessoa": slug,
                            "weight": 1.0,
                            "artifact_dir": f"knowledge/{bucket}/dna/persons/{slug}/",
                        }
                    ]
                },
                "composition": composition,
            },
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        ),
    }

    if dry_run:
        return {
            "created": False,
            "reason": "dry_run",
            "agent_dir": str(agent_dir),
            "files": list(file_plan.keys()),
        }

    try:
        agent_dir.mkdir(parents=True, exist_ok=False)
    except FileExistsError:
        # Race: another process created it between our exists() check and now.
        return {
            "created": False,
            "reason": "race -- agent directory appeared mid-creation",
            "agent_dir": str(agent_dir),
            "files": [],
        }
    except Exception as exc:
        return {
            "created": False,
            "error": f"mkdir failed: {exc}",
            "agent_dir": str(agent_dir),
            "files": [],
        }

    written: list[str] = []
    for fname, content in file_plan.items():
        try:
            (agent_dir / fname).write_text(content, encoding="utf-8")
            written.append(fname)
        except Exception as exc:  # pragma: no cover - non-fatal
            logger.warning("Failed to write %s for %s: %s", fname, slug, exc)

    logger.info(
        "Auto-created agent skeleton at %s (%d files, bucket=%s, dna_total=%d)",
        agent_dir,
        len(written),
        bucket,
        dna_total,
    )

    return {
        "created": True,
        "agent_dir": str(agent_dir),
        "files": written,
        "bucket": bucket,
        "dna_total": dna_total,
    }


def ensure_agent_skeleton_for_slug(
    slug: str,
    bucket: str,
    *,
    sources_count: int = 0,
) -> dict[str, Any]:
    """Idempotent helper: ensure an agent skeleton exists for the slug.

    Wrapper around ``create_agent_skeleton`` that swallows ALL exceptions and
    returns a structured result.  Designed to be called from ``cmd_finalize``
    where pipeline integrity (Art. XII) requires non-fatal observability.

    Args:
        slug: Person slug (kebab-case).
        bucket: ``"external" | "business"``.
        sources_count: Optional count of source files processed.

    Returns:
        Same shape as ``create_agent_skeleton``.  On unexpected exception
        returns ``{"created": False, "error": ..., "agent_dir": "", "files": []}``.
    """
    try:
        return create_agent_skeleton(slug, bucket, sources_count=sources_count)
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning("ensure_agent_skeleton_for_slug failed for %s: %s", slug, exc)
        return {
            "created": False,
            "error": str(exc),
            "agent_dir": "",
            "files": [],
        }
