"""Role Tracker — Cargo Agent Auto-Creation.

Story MCE-11.8: Detects cargo role mentions in per-slug INSIGHTS-STATE.json,
maintains a ROLE-TRACKING-CARGO.json registry, and auto-creates minimal
cargo agent scaffolds when a role reaches the CRITICAL threshold (>= 10 mentions).

Design decisions:
- No LLM calls: keyword-based detection only (cost efficiency, precision over recall).
- Non-blocking from cmd_finalize: exceptions are caught and logged as warnings.
- Coexists with existing ROLE-TRACKING.json (keyed by person, different schema).
  This module writes ROLE-TRACKING-CARGO.json only.
- Auto-creation only for roles defined in ROLE_AREA_MAP. Unknown roles are tracked
  but never auto-created to prevent noise.
- Idempotent: if agent directory already exists, skips creation silently.
- Semantic filter (Story MCE-semantic-filter): PASSIVE mentions (citations of third
  parties) are excluded from counts. Only ACTIVE mentions (attributed perspective,
  imperatives, possessive 1st person) advance the counter. Threshold remains 10.

AUTO-GENERATED by role_tracker.py [Story MCE-11.8]
"""

from __future__ import annotations

import json
import logging
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

THRESHOLD_CRITICAL = 10
THRESHOLD_IMPORTANT = 5
# 1-4 = TRACK

# ---------------------------------------------------------------------------
# Semantic filter: PASSIVE vs ACTIVE mention classification
# ---------------------------------------------------------------------------

# Patterns that strongly signal a PASSIVE mention (citation of a third party,
# not an attributed perspective). Matched against a ±80-char window around
# the role keyword match.
PASSIVE_MARKERS_REGEX: list[str] = [
    r"\bde\s+(uma|um)\s+(empresa|cliente|consultoria)\b",  # "de uma empresa", "de um cliente"
    r"\bconheci\s+(um|uma)\b",                              # "conheci um Closer"
    r"\bconsultei\s+(um|uma)\b",                            # "consultei um CFO"
    r"\bvi\s+(um|uma)\b",                                   # "vi um BDR fazer"
    r"\b(do|da|dos|das)\s+meu(s)?\s+(cliente|amigo|conhecido)",  # "do meu cliente"
    r"\bcliente\s+(meu|nosso|dele|dela)\b",                 # "cliente meu CFO"
    r"\b(esse|essa|aquele|aquela)\s+(cara|moço|mocо|pessoa)\b",  # "esse cara CFO"
]

# Patterns that strongly signal an ACTIVE mention (attributed perspective,
# imperative, possessive 1st person tied to the role).
ACTIVE_MARKERS_REGEX: list[str] = [
    r"\bcomo\s+(um|uma|o|a)\s+",                            # "como um CFO"
    r"\bse\s+você\s+(é|for|fosse)\s+",                      # "se você é CFO"
    r"\bvocê\s+precisa\s+",                                 # "você precisa"
    r"\b(faça|pense|aja|seja)\s+",                          # imperatives
    r"\b(meu|minha|nosso|nossa)\s+(cfo|cro|coo|closer|bdr|setter|sds|lns)",  # possessive 1st person (lowercased)
    r"\bo\s+(papel|trabalho|função|funcao|job)\s+d[oa]\s+",  # "o papel do CFO"
    r"\bdeve(m)?\s+(fazer|pensar|usar|aplicar)\b",           # "o Closer deve fazer X"
]

# Window size (chars) around the keyword match used for context evaluation
_CLASSIFY_WINDOW = 80


def _classify_mention(text: str, match_start: int, match_end: int) -> str:
    """Classify a role keyword match as ACTIVE, PASSIVE, or AMBIGUOUS.

    Extracts a ±_CLASSIFY_WINDOW-char window around the match and tests it
    against ACTIVE and PASSIVE marker patterns.

    Returns:
        "ACTIVE"    — at least one ACTIVE_MARKER matched (wins over PASSIVE).
        "PASSIVE"   — at least one PASSIVE_MARKER matched AND no ACTIVE marker.
        "AMBIGUOUS" — neither ACTIVE nor PASSIVE matched; treated as ACTIVE
                      (fail-open: avoid false negatives).

    Examples:
        >>> _classify_mention("o cfo de uma empresa que consultei fez X", 2, 5)
        'PASSIVE'
        >>> _classify_mention("pense como um cfo na hora de avaliar", 14, 17)
        'ACTIVE'
        >>> _classify_mention("o cfo definiu a estrategia do trimestre", 2, 5)
        'AMBIGUOUS'
    """
    window_start = max(0, match_start - _CLASSIFY_WINDOW)
    window_end = min(len(text), match_end + _CLASSIFY_WINDOW)
    window = text[window_start:window_end]

    # Check ACTIVE first — it wins even if PASSIVE also matches
    for pattern in ACTIVE_MARKERS_REGEX:
        if re.search(pattern, window):
            return "ACTIVE"

    for pattern in PASSIVE_MARKERS_REGEX:
        if re.search(pattern, window):
            return "PASSIVE"

    return "AMBIGUOUS"  # default: treat as ACTIVE (fail-open)


# Keyword groups -> normalized role name.
# Lists are ordered from most-specific to most-generic to avoid partial matches.
# All keywords are lowercase and matched case-insensitively.
CARGO_ROLE_KEYWORDS: dict[str, list[str]] = {
    "Closer": [
        "sales closer",
        "closer de vendas",
        r"\bcloser\b",
        r"\bfechador\b",
    ],
    "BDR": [
        "business development rep",
        "business development representative",
        r"\bpré-vendas\b",
        r"\bpre-vendas\b",
        r"\bbdr\b",
    ],
    "Sales Manager": [
        "gerente de vendas",
        "gestor comercial",
        "sales manager",
    ],
    "Head of Ops": [
        "head of operations",
        "head of ops",
        "ops manager",
        "gerente de operações",
        "gerente de operacoes",
    ],
    "CRO": [
        "chief revenue officer",
        "diretor de receita",
        r"\bcro\b",
    ],
    "CFO": [
        "chief financial officer",
        "diretor financeiro",
        r"\bcfo\b",
    ],
    "COO": [
        "chief operating officer",
        "diretor de operações",
        "diretor de operacoes",
        r"\bcoo\b",
    ],
    "SDS": [
        "qualification specialist",
        r"\bsds\b",
        r"\bsetter\b",
    ],
    "LNS": [
        "nutrição de leads",
        "nutricao de leads",
        "lead nurturing",
        r"\blns\b",
    ],
}

# Maps normalized role name -> area folder under agents/external/cargo/
ROLE_AREA_MAP: dict[str, str] = {
    "Closer": "sales",
    "BDR": "sales",
    "Sales Manager": "sales",
    "SDS": "sales",
    "LNS": "sales",
    "CRO": "c-level",
    "CFO": "c-level",
    "COO": "c-level",
    "Head of Ops": "ops",
}


def _project_root() -> Path:
    """Resolve project root via git toplevel or fallback to 4 levels up from this file."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        return Path(result.stdout.strip())
    except Exception:
        # Fallback: engine/intelligence/pipeline/mce/ -> 4 levels up
        return Path(__file__).resolve().parents[4]


def _role_slug(role_name: str) -> str:
    """Convert 'Head of Ops' -> 'head-of-ops'."""
    return re.sub(r"[^a-z0-9]+", "-", role_name.lower()).strip("-")


def _compute_priority(count: int) -> str:
    if count >= THRESHOLD_CRITICAL:
        return "CRITICAL"
    if count >= THRESHOLD_IMPORTANT:
        return "IMPORTANT"
    return "TRACK"


# ---------------------------------------------------------------------------
# Core: scan INSIGHTS-STATE for role mentions
# ---------------------------------------------------------------------------


def scan_for_cargo_roles(slug: str) -> list[dict[str, Any]]:
    """Scan per-slug INSIGHTS-STATE.json and count cargo role keyword mentions.

    Args:
        slug: Pipeline slug (e.g., "LO-0001").

    Returns:
        List of RoleEntry dicts with keys:
            normalized_name, mention_count, sources, priority, agent_exists, agent_path
    """
    root = _project_root()
    artifacts_dir = root / ".data" / "artifacts"

    # Canonical path (matches orchestrate._insights_state_path):
    #   .data/artifacts/insights/{slug}/INSIGHTS-STATE.json
    insights_path = artifacts_dir / "insights" / slug / "INSIGHTS-STATE.json"
    if not insights_path.exists():
        # Secondary: .data/artifacts/mce/{slug}/INSIGHTS-STATE.json (legacy MCE layout)
        insights_path = artifacts_dir / "mce" / slug / "INSIGHTS-STATE.json"
    if not insights_path.exists():
        # Tertiary: flat layout .data/artifacts/{slug}/INSIGHTS-STATE.json (pre-migration)
        insights_path = artifacts_dir / slug / "INSIGHTS-STATE.json"
    if not insights_path.exists():
        # Final fallback: .data/artifacts/INSIGHTS-STATE-{slug}.json
        insights_path = artifacts_dir / f"INSIGHTS-STATE-{slug}.json"
    if not insights_path.exists():
        logger.debug("role_tracker: INSIGHTS-STATE not found for slug=%s, skipping scan", slug)
        return []

    try:
        raw = json.loads(insights_path.read_text(encoding="utf-8"))
    except Exception as exc:
        logger.warning("role_tracker: failed to read INSIGHTS-STATE for %s: %s", slug, exc)
        return []

    # Multi-schema detection (MCE-11.8):
    # Schema A: legacy lista direta
    if isinstance(raw, list):
        insights = raw
    # Schema B: top-level {"insights": [...]}
    elif isinstance(raw, dict) and "insights" in raw and isinstance(raw["insights"], list):
        insights = raw["insights"]
    # Schema C: aninhado {"persons": {"Name": {"insights": [...]}}}
    elif isinstance(raw, dict) and "persons" in raw and isinstance(raw["persons"], dict):
        insights = []
        for person_data in raw["persons"].values():
            if isinstance(person_data, dict):
                pi = person_data.get("insights", [])
                if isinstance(pi, list):
                    insights.extend(pi)
    # Schema D: wrapper {"insights_state": {"persons": {"Name": {"insights": [...]}}}}
    elif isinstance(raw, dict) and "insights_state" in raw and isinstance(raw["insights_state"], dict):
        inner = raw["insights_state"]
        insights = []
        persons_map = inner.get("persons", {})
        if isinstance(persons_map, dict):
            for person_data in persons_map.values():
                if isinstance(person_data, dict):
                    pi = person_data.get("insights", [])
                    if isinstance(pi, list):
                        insights.extend(pi)
    else:
        insights = []
        logger.warning("role_tracker: unknown INSIGHTS-STATE schema for slug=%s", slug)

    # Count per-role across all insight text fields.
    # active_counts: mentions that passed the semantic filter (ACTIVE or AMBIGUOUS).
    # passive_counts: mentions rejected as PASSIVE citations of third parties.
    active_counts: dict[str, int] = {role: 0 for role in CARGO_ROLE_KEYWORDS}
    passive_counts: dict[str, int] = {role: 0 for role in CARGO_ROLE_KEYWORDS}

    def _search_text(text: str) -> None:
        if not text:
            return
        lowered = text.lower()
        for role_name, patterns in CARGO_ROLE_KEYWORDS.items():
            for pattern in patterns:
                # Patterns starting with \b are regex, rest are plain substring
                if pattern.startswith(r"\b") or pattern.startswith("(?"):
                    match = re.search(pattern, lowered)
                    if match:
                        classification = _classify_mention(
                            lowered, match.start(), match.end()
                        )
                        if classification == "PASSIVE":
                            passive_counts[role_name] += 1
                        else:
                            # ACTIVE or AMBIGUOUS both advance the active counter
                            active_counts[role_name] += 1
                        break  # count once per insight-field per role
                else:
                    idx = lowered.find(pattern)
                    if idx != -1:
                        classification = _classify_mention(
                            lowered, idx, idx + len(pattern)
                        )
                        if classification == "PASSIVE":
                            passive_counts[role_name] += 1
                        else:
                            active_counts[role_name] += 1
                        break

    for insight in insights:
        if not isinstance(insight, dict):
            continue
        _search_text(insight.get("insight", ""))
        _search_text(insight.get("quote", ""))
        tags = insight.get("tags", insight.get("tag", ""))
        if isinstance(tags, list):
            _search_text(" ".join(tags))
        else:
            _search_text(str(tags) if tags else "")

    # Telemetry log: one line per role that had any mention (active or passive)
    for role_name in CARGO_ROLE_KEYWORDS:
        a = active_counts[role_name]
        p = passive_counts[role_name]
        if a + p > 0:
            logger.info(
                "role_tracker: slug=%s role=%-20s active=%d passive_filtered=%d",
                slug,
                role_name,
                a,
                p,
            )

    # Build result entries (only roles with at least 1 ACTIVE mention).
    # mention_count = active_count for backward compatibility with threshold logic.
    cargo_agents_root = root / "agents" / "external" / "cargo"
    entries = []
    for role_name in CARGO_ROLE_KEYWORDS:
        count = active_counts[role_name]
        if count == 0:
            continue
        area = ROLE_AREA_MAP.get(role_name)
        slug_role = _role_slug(role_name)
        agent_path_rel: str | None = None
        agent_exists = False
        if area:
            candidate = cargo_agents_root / area / slug_role / "AGENT.md"
            if candidate.exists():
                agent_exists = True
                agent_path_rel = f"agents/external/cargo/{area}/{slug_role}/"
        entries.append(
            {
                "normalized_name": role_name,
                "mention_count": count,           # ACTIVE only — threshold uses this
                "passive_count_filtered": passive_counts[role_name],
                "sources": [slug],
                "priority": _compute_priority(count),
                "agent_exists": agent_exists,
                "agent_path": agent_path_rel,
            }
        )

    return entries


# ---------------------------------------------------------------------------
# State management: ROLE-TRACKING-CARGO.json
# ---------------------------------------------------------------------------


def _load_cargo_tracking(root: Path) -> dict[str, Any]:
    tracking_path = root / ".data" / "artifacts" / "ROLE-TRACKING-CARGO.json"
    if tracking_path.exists():
        try:
            return json.loads(tracking_path.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.warning("role_tracker: could not parse ROLE-TRACKING-CARGO.json: %s", exc)
    return {"last_updated": "", "roles": {}}


def _save_cargo_tracking(root: Path, state: dict[str, Any]) -> None:
    tracking_path = root / ".data" / "artifacts" / "ROLE-TRACKING-CARGO.json"
    tracking_path.parent.mkdir(parents=True, exist_ok=True)
    tracking_path.write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def update_role_tracking_state(
    slug: str,
    new_entries: list[dict[str, Any]],
    root: Path | None = None,
) -> dict[str, Any]:
    """Merge new role entries into ROLE-TRACKING-CARGO.json.

    For each role entry from the current scan, merges mention counts and
    updates source list. Recalculates priority after merge.

    Args:
        slug: Source slug being finalized.
        new_entries: Output of scan_for_cargo_roles(slug).
        root: Project root (resolved automatically if None).

    Returns:
        Updated tracking state dict.
    """
    if root is None:
        root = _project_root()
    state = _load_cargo_tracking(root)
    roles: dict[str, Any] = state.get("roles", {})

    cargo_agents_root = root / "agents" / "external" / "cargo"

    for entry in new_entries:
        role_name = entry["normalized_name"]
        area = ROLE_AREA_MAP.get(role_name)
        slug_role = _role_slug(role_name)

        # Refresh agent_exists on every update (agent may have been created since last run)
        agent_exists = False
        agent_path_rel: str | None = None
        if area:
            candidate = cargo_agents_root / area / slug_role / "AGENT.md"
            if candidate.exists():
                agent_exists = True
                agent_path_rel = f"agents/external/cargo/{area}/{slug_role}/"

        if role_name not in roles:
            roles[role_name] = {
                "normalized_name": role_name,
                "mention_count": entry["mention_count"],
                "sources": list(entry["sources"]),
                "priority": entry["priority"],
                "agent_exists": agent_exists,
                "agent_path": agent_path_rel,
                "last_updated": datetime.now(UTC).isoformat(),
            }
        else:
            existing = roles[role_name]
            existing["mention_count"] = existing.get("mention_count", 0) + entry["mention_count"]
            sources_set = set(existing.get("sources", []))
            sources_set.update(entry["sources"])
            existing["sources"] = sorted(sources_set)
            existing["priority"] = _compute_priority(existing["mention_count"])
            existing["agent_exists"] = agent_exists
            existing["agent_path"] = agent_path_rel
            existing["last_updated"] = datetime.now(UTC).isoformat()

    state["roles"] = roles
    state["last_updated"] = datetime.now(UTC).isoformat()
    _save_cargo_tracking(root, state)
    return state


# ---------------------------------------------------------------------------
# Cargo agent auto-creation
# ---------------------------------------------------------------------------

_AGENT_MD_TEMPLATE = """\
---
id: {slug_role}
role: "{role_name}"
area: {area}
version: "1.0.0"
status: auto-generated
created: {created_date}
# AUTO-GENERATED by role_tracker.py [Story MCE-11.8] — refine manually
---

# AGENT-{role_upper}: {role_name}

> **Versao:** 1.0.0
> **Area:** {area_title}
> **Status:** AUTO-GENERATED — refine after accumulating more source material
> **Criado em:** {created_date}

---

## DOSSIE EXECUTIVO

### Missao
Agente funcional de **{role_name}** gerado automaticamente pelo pipeline MCE
ao detectar {threshold}+ mencoes deste role nos insights processados.

Fontes que originaram este agente: {sources_str}

---

## CAPABILITIES (a preencher manualmente)

- [ ] Definir escopo de responsabilidades
- [ ] Mapear frameworks operacionais do role
- [ ] Integrar fontes de conhecimento relevantes

---

## INTERFACES

| Agente | Relacionamento |
|--------|----------------|
| (a definir) | — |

---

*AGENT.md v1.0.0 — AUTO-GENERATED*
*Refine manually after enough source material is available.*
"""

_SOUL_MD_TEMPLATE = """\
---
id: {slug_role}
role: "{role_name}"
version: "1.0.0"
created: {created_date}
# AUTO-GENERATED by role_tracker.py [Story MCE-11.8] — refine manually
---

# SOUL: {role_name}

> **Versao:** 1.0.0
> **Natureza:** FUNCIONAL
> **Status:** AUTO-GENERATED — identidade minima, refine manualmente

---

## IDENTITY CARD

```
╔══════════════════════════════════════════════════╗
║                                                  ║
║   {role_upper_padded}  ║
║                                                  ║
╚══════════════════════════════════════════════════╝
```

## QUEM SOU EU

Sou o especialista em **{role_name}** dentro do ecossistema.
Este perfil foi gerado automaticamente e precisa ser refinado
com base no material de conhecimento acumulado.

---

*SOUL.md v1.0.0 — AUTO-GENERATED*
"""

_MEMORY_MD_TEMPLATE = """\
# MEMORIA: {role_name}

> **Agente:** `agents/external/cargo/{area}/{slug_role}/AGENT.md`
> **Criada:** {created_date}
> **Versao:** 1.0.0
> **Status:** AUTO-GENERATED by role_tracker.py [Story MCE-11.8]

---

## ACUMULADO

*(Nenhum insight acumulado ainda — aguardando material de treinamento.)*

---

## HISTORICO

| Data | Tipo | Descricao |
|------|------|-----------|
| {created_date} | criacao | Agente auto-gerado ao atingir {threshold}+ mencoes |

"""


def cmd_create_cargo_agent(
    role_name: str,
    area: str,
    sources: list[str],
    root: Path | None = None,
) -> dict[str, Any]:
    """Create minimal cargo agent directory structure.

    Creates:
        agents/external/cargo/{area}/{role-slug}/
            AGENT.md
            SOUL.md
            MEMORY.md

    Idempotent: if AGENT.md already exists, returns early with agent_exists=True.

    Args:
        role_name: Normalized role name (e.g., "Head of Ops").
        area: Area folder (e.g., "ops", "sales", "c-level").
        sources: List of slugs that mentioned this role.
        root: Project root (resolved automatically if None).

    Returns:
        Result dict with keys: created (bool), path (str), skipped_reason (str|None).
    """
    if root is None:
        root = _project_root()

    slug_role = _role_slug(role_name)
    agent_dir = root / "agents" / "external" / "cargo" / area / slug_role
    agent_md_path = agent_dir / "AGENT.md"

    if agent_md_path.exists():
        return {
            "created": False,
            "path": str(agent_dir.relative_to(root)),
            "skipped_reason": "AGENT.md already exists",
        }

    agent_dir.mkdir(parents=True, exist_ok=True)
    created_date = datetime.now(UTC).date().isoformat()
    sources_str = ", ".join(sources) if sources else "unknown"
    role_upper = role_name.upper().replace(" ", "_")
    area_title = area.replace("-", " ").title()
    padded = role_name.upper().center(48)
    padded = padded[:48]  # max 48 chars to fit box

    agent_md_path.write_text(
        _AGENT_MD_TEMPLATE.format(
            slug_role=slug_role,
            role_name=role_name,
            area=area,
            area_title=area_title,
            role_upper=role_upper,
            created_date=created_date,
            threshold=THRESHOLD_CRITICAL,
            sources_str=sources_str,
        ),
        encoding="utf-8",
    )

    (agent_dir / "SOUL.md").write_text(
        _SOUL_MD_TEMPLATE.format(
            slug_role=slug_role,
            role_name=role_name,
            role_upper=role_name.upper(),
            role_upper_padded=padded,
            created_date=created_date,
        ),
        encoding="utf-8",
    )

    (agent_dir / "MEMORY.md").write_text(
        _MEMORY_MD_TEMPLATE.format(
            role_name=role_name,
            area=area,
            slug_role=slug_role,
            created_date=created_date,
            threshold=THRESHOLD_CRITICAL,
        ),
        encoding="utf-8",
    )

    rel_path = str(agent_dir.relative_to(root))
    logger.info(
        "role_tracker: auto-created cargo agent %s at %s (sources: %s)",
        role_name,
        rel_path,
        sources_str,
    )
    print(
        f"[role_tracker] AUTO-CREATED cargo agent '{role_name}' -> {rel_path}",
        flush=True,
    )
    return {
        "created": True,
        "path": rel_path,
        "skipped_reason": None,
    }


# ---------------------------------------------------------------------------
# Entry point called from cmd_finalize
# ---------------------------------------------------------------------------


def track_roles_and_create(slug: str) -> dict[str, Any]:
    """Scan slug for role mentions, update tracking state, auto-create CRITICAL agents.

    This is the single entry point called from cmd_finalize as a non-blocking
    subphase. Internal exceptions bubble up to the caller which wraps in try/except.

    Args:
        slug: Pipeline slug being finalized.

    Returns:
        Summary dict with: slug, roles_scanned, critical_created, state_updated.
    """
    root = _project_root()

    # 1. Scan
    entries = scan_for_cargo_roles(slug)
    if not entries:
        logger.debug("role_tracker: no role mentions found for slug=%s", slug)
        return {
            "slug": slug,
            "roles_scanned": 0,
            "critical_created": [],
            "state_updated": False,
        }

    # 2. Merge into tracking state
    update_role_tracking_state(slug, entries, root=root)

    # 3. Auto-create CRITICAL agents that don't exist yet
    # D4 gate: each CRITICAL role asks decision_gateway before auto-creating.
    # Non-blocking: if gateway is unavailable, default to False (do not create)
    # to avoid unreviewed auto-creation noise.
    created: list[str] = []
    for entry in entries:
        if entry["priority"] != "CRITICAL":
            continue
        if entry["agent_exists"]:
            continue
        role_name = entry["normalized_name"]
        area = ROLE_AREA_MAP.get(role_name)
        if not area:
            logger.debug(
                "role_tracker: role '%s' has no area mapping, skipping auto-creation",
                role_name,
            )
            continue

        # D4 — prompt user (or log in non-interactive mode) before auto-creating
        _d4_approved = False
        try:
            from engine.intelligence.pipeline.mce.decision_gateway import (
                decide_d4_create_cargo_agent,
            )

            _d4_approved = decide_d4_create_cargo_agent(
                role=role_name,
                count=entry["mention_count"],
                slug=slug,
            )
            logger.info(
                "role_tracker: D4 decision for role=%s count=%d → %s",
                role_name,
                entry["mention_count"],
                _d4_approved,
            )
        except Exception as _d4_exc:
            logger.warning(
                "role_tracker: D4 decision_gateway unavailable for role=%s, defaulting to False: %s",
                role_name,
                _d4_exc,
            )

        if not _d4_approved:
            logger.info(
                "role_tracker: D4=False — skipping auto-creation for role=%s (slug=%s)",
                role_name,
                slug,
            )
            continue

        result = cmd_create_cargo_agent(
            role_name=role_name,
            area=area,
            sources=entry["sources"],
            root=root,
        )
        if result.get("created"):
            created.append(role_name)
            # Refresh agent_exists in tracking state after creation
            state = _load_cargo_tracking(root)
            if role_name in state.get("roles", {}):
                slug_role = _role_slug(role_name)
                state["roles"][role_name]["agent_exists"] = True
                state["roles"][role_name]["agent_path"] = (
                    f"agents/external/cargo/{area}/{slug_role}/"
                )
                _save_cargo_tracking(root, state)

    logger.info(
        "role_tracker: slug=%s entries=%d critical_created=%s",
        slug,
        len(entries),
        created,
    )
    return {
        "slug": slug,
        "roles_scanned": len(entries),
        "critical_created": created,
        "state_updated": True,
    }
